### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x715cde]

### ISSUE THREAD

**Issue by zameji** [cloudflare/cf-terraforming#555]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

0.12.0

### Expected outcome

The resource should have been generated successfully.

### Actual outcome

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x715cde]

goroutine 1 [running]:
github.com/cloudflare/cloudflare-go.(*API).makeRequestContext(0xa4f24a?, {0xb362d0?, 0xc0000a4000?}, {0xa4b3ba?, 0x18?}, {0xc003540a80?, 0x4148f6?}, {0x0?, 0x0?})
	/home/runner/go/pkg/mod/github.com/cloudflare/cloudflare-go@v0.63.0/cloudflare.go:172 +0x3e
github.com/cloudflare/cloudflare-go.(*API).ListOriginCACertificates(0x7ffe4d443c82?, {0xb362d0, 0xc0000a4000}, {{0x7ffe4d443caa?, 0xc000187680?}})
	/home/runner/go/pkg/mod/github.com/cloudflare/cloudflare-go@v0.63.0/origin_ca.go:129 +0x9b
github.com/cloudflare/cf-terraforming/internal/app/cf-terraforming/cmd.generateResources.func1(0xeb1260?, {0xa4b7f3?, 0x6?, 0x6?})
	/home/runner/work/cf-terraforming/cf-terraforming/internal/app/cf-terraforming/cmd/generate.go:601 +0x4166
github.com/spf13/cobra.(*Command).execute(0xeb1260, {0xc0000ae4e0, 0x6, 0x6})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x8[47](https://github.com/TomesGmbH/idana-data-cron-jobs/actions/runs/4690665360/jobs/8314073015#step:5:48)
github.com/spf13/cobra.(*Command).ExecuteC(0xeb0f80)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/cloudflare/cf-terraforming/internal/app/cf-terraforming/cmd.Execute()
	/home/runner/work/cf-terraforming/cf-terraforming/internal/app/cf-terraforming/cmd/root.go:30 +0x25
main.main()
	/home/runner/work/cf-terraforming/cf-terraforming/cmd/cf-terraforming/main.go:8 +0x17
```

### Steps to reproduce

1. Create a github action:

```YAML
name: "Export"

on:
  workflow_dispatch:

jobs:
  Cloudflare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Checkout latest Cloudflare-Terraforming release
        env:
          GH_TOKEN: ${{ github.token }}  
        run: |
          mkdir "$GITHUB_WORKSPACE/cf_terraforming"
          cd "$GITHUB_WORKSPACE/cf_terraforming"
          gh release download --pattern="*_linux_amd64.tar.gz" -R "https://github.com/cloudflare/cf-terraforming"
          tar -xf *.tar.gz
          ./cf-terraforming version
          
      - name: Back-Up cloudflare settings
        run: |
          mkdir cf
          cd cf
          echo $'terraform {\n  required_providers {\n    cloudflare = {\n      source = "cloudflare/cloudflare"\n      version = "~> 3.0"\n    }\n  }\n}' > "cloudflare.tf"
          terraform init
          "$GITHUB_WORKSPACE/cf_terraforming/cf-terraforming" -t "$CLOUDFLARE_API_TOKEN" generate --resource-type cloudflare_origin_ca_certificate --zone "$ZONE_ID"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          ZONE_ID: ${{ secrets.ZONE_ID}}

```

3. Run it
